export const PAGE_TITLE_EXIT_DURATION_S = 0.9
export const PAGE_TITLE_EXIT_DURATION_MS = PAGE_TITLE_EXIT_DURATION_S * 1000
export const PAGE_TITLE_EXIT_EASE = 'power3.in'
export const PAGE_TITLE_EXIT_DISTANCE = '15vh'
export const PAGE_TITLE_SECONDARY_EXIT_DISTANCE = '10vh'
